### ISSUE TITLE
Images lose quality when saving the TMongoWire.

### ISSUE THREAD

**Issue by OneideLuizSchneider** [stijnsanders/TMongoWire#26]
hi
I have a problem when I upload large files such as videos.
They are losing quality.

So I changed the value of the const 'mongoStreamDefaultChunkSize' for $ E4E1C0, which is equal to 15000000 in decimal. With that the video did not lose more quality.

Same problem happens with images, if I leave the default value of const 'mongoStreamDefaultChunkSize'.

In my view this is not correct because the database is very large. Any suggestion?

**Comment by stijnsanders** [comment]
If I have a look here:
https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/grid/file/chunk.rb#L32
and
http://docs.mongodb.org/manual/core/gridfs/
the maximum is 255*1024 (=$3FC00) and that's what in the source.
You cannot make the database smaller by changing this, because the database will be at least as large as the files you store in it, except for overhead which you can control to some extent, but what you need to make GridFS work.

**Comment by oneidewarrior** [comment]
hi
If you leave the standard $ 3FC00 = 255K then the files as images and large videos are corrupted if you make a test with images above 10 megabytes in demo2 he will lose quality and sometimes even becoming unreadable.

and if you do the same test with java or PHP does not lose quality.

**Comment by oneidewarrior** [comment]
Here is a picture to show WHAT'm thinking - >> http://i.imgur.com/hwkIVyJ.jpg

**Comment by stijnsanders** [comment]
I tried with a few big files, I don't have any trouble uploading files of even +100MB. Could you share code? Ideally a small program that only demonstrates what goes wrong.

**Comment by OneideLuizSchneider** [comment]
hi,
I used his demo2. He only loses quality, the size is the same.

I used this image -> http://www.microsys.inf.br/publico/13_ORIGINAL.jpg

Please UPLOAD that image and after her return, then open it to see that lost quality, but the size is the same.

**Comment by stijnsanders** [comment]
I tried it with that image and `TMongoWire\demo\example2\mwx2.exe`, and get the exact binary identical file.

**Comment by OneideLuizSchneider** [comment]
hi..

I downloaded the new version and now worked.
You made some adjustment? I have noticed that commits.

**Comment by stijnsanders** [comment]
I assume my recent changes solved the problem.
