### ISSUE TITLE
[POSSIBLE PATCH] Delphi XE8 support

### ISSUE THREAD

**Issue by silvioprog** [stijnsanders/TMongoWire#28]
Hello,

Is there any plan to make it compatible with Delphi XE 8? I tried to use that, but the bsonDoc unit doesn't compile on this compiler.

Thank you!

**Comment by silvioprog** [comment]
Additional note: I did some changes in my local copy and it worked like a charme here in XE 8 (I need test it in D7), if you prefer, I can attach a patch showing the changes.

**Comment by stijnsanders** [comment]
Yes, please do

**Comment by stijnsanders** [comment]
Apparently the signature for TStream.Seek changed slightly between Delphi versions. I've modified the `$IFDEF` into `$IF CompilerVersion>` to make it work for even newer versions of Delphi. [...](https://github.com/stijnsanders/TMongoWire/commit/622780cd58f3ccc17c85d00d2da5c3ffbd0b83bb#diff-115a77960ed9ae3495957dc88f9eef9f5eca0d060a240d3f6f4a6267e344859eR746)
