### ISSUE TITLE
Compiling Delphi Berlin 10.1

### ISSUE THREAD

**Issue by OneideLuizSchneider** [stijnsanders/TMongoWire#34]
Hi,
For commit in Delphi Berlin must alter this variables.

Example:
p,q:int64;
to
 p,q:UInt64;

or directives compilation:

{$IFDEF VER310}
  p,q:UInt64;
{$ELSE}
  p,q:int64;
{$ENDIF}

Example in project :
https://github.com/OneideLuizSchneider/RiceFramework/tree/master/Delphi/TMongoWire

**Comment by stijnsanders** [comment]
Thank you, see my recent commit
