### ISSUE TITLE
Run Javascript

### ISSUE THREAD

**Issue by scaleman114** [stijnsanders/TMongoWire#38]
Hi I do not seem to be able to get your javascript example to work.
Wire.Insert('system.js',BSON(['_id','x1','value',bsonJavaScriptCodePrefix+
    'function(){return {test:123};}']));
 d:=Wire.Get('$cmd',BSON(['eval','x1();']));
  Memo1.Text:=BsonToJson(IUnknown(d['retval']) as IBSONDocument);
The error I am getting is: Could not convert variant of type (Null) into type (Unknown)

**Comment by scaleman114** [comment]
Sorry I have sorted it, it was an authorisation issue.

**Comment by stijnsanders** [comment]
ok, I'm glad it works now
