### ISSUE TITLE
Delphi XE Error

### ISSUE THREAD

**Issue by DDAGitHub** [stijnsanders/TMongoWire#40]
Hello.
Delphi XE, mwx1  example:
I get an error on creating New record:
_Unsupported variant type 0102 "id"_

**Comment by stijnsanders** [comment]
Ah, apparently _modern_ Delphi versions define this:

      varUString  = $0102; { Unicode string 258 } {not OLE compatible }

And since I've switched from `OleVariant` to `Variant` I will have to add it. See my most recent commit. Let me know if this works as expected for you.

**Comment by DDAGitHub** [comment]
Now it works, thank you!
