### ISSUE TITLE
Expression too complex

### ISSUE THREAD

**Issue by Skullw1ng** [stijnsanders/TMongoWire#50]
Hello!

Today I got the error "E2156 Expression too complex", does anyone know what I can do about this? I guess splitting the data inside JSON([]) up would be possible but I would like to keep it as a single entry.

Thanks,
Etienne

**Comment by stijnsanders** [comment]
Care to share more code? It says [here](http://docwiki.embarcadero.com/RADStudio/Sydney/en/E2156_Expression_too_complicated_(Delphi)) to split up the code. If you're using JSON([]) to create a query document for _every call_ I would consider keeping a copy of the JSON document and filling in the values that change with every call. (Pay attention to multi-thread issues if you're calling from multiple threads...)

**Comment by Skullwing** [comment]
I took the json file and added in the values that I needed string by string in json, then parsed it into the IJSONDocument. Works fine.

**Comment by stijnsanders** [comment]
Please replace the `document.Parse` call with this code. It is very important not to work with 'JSON in string form' unless you really absolutely have to.

    document['_id']:=mongoObjectID;
    document['Test']:='Hi';
    document['Test1']:='Cool';
