### ISSUE TITLE
Creating Databases and Collections

### ISSUE THREAD

**Issue by Skullwing** [stijnsanders/TMongoWire#51]
Hello!
Is it possible to create databases and collections using this framework?

Thanks

**Comment by stijnsanders** [comment]
TMongoWire is not actually a 'full' MongoDB driver, and a number of things are only available of you make a call to `$cmd` yourself. Have a look at the existing `$cmd` calls, [for example ping](https://github.com/stijnsanders/TMongoWire/blob/master/mongoWire.pas#L514), and apply this to the [create command](https://docs.mongodb.com/manual/reference/command/create/).
